.MODEL SMALL
.STACK 64
.DATA
	PA EQU 0H ;DEFINING PORTS
	PB EQU 1H ;DEFINING PORTS
	PC EQU 2H ;DEFINING PORTS
	CR EQU 3H ;DEFINING PORTS
.CODE

SET_7SEG PROC FAR
	;SETTING THE AX FOR THE 7-SEGMENT (RESULT)
	;BX CONTAINS THE NUMBER THAT WE SHOULD SHOW IN 7-SEGMENT
	

SET_7SEG ENDP

MAIN    PROC FAR
        MOV AX,@DATA
        MOV DS,AX
		
		
		
LOOP_START:
		OUT PA, 1111B ; SETTING ALL KEYPAD INPUT TO 1
		
		IN DL, PC ; READING INPUTS
		
		CMP DL, 001B
		JE COLUMN1 ; COLUMN 1 OF KEYPAD IS PRESSED
		CMP DL, 010B
		JE COLUMN2 ; COLUMN 2 OF KEYPAD IS PRESSED
		CMP DL, 100B
		JE COLUMN3 ; COLUMN 3 OF KEYPAD IS PRESSED
		JMP LOOP_START
KEYPAD_BUTTON_FOUND:
		
		JMP LOOP_START
		
COLUMN1:
		OUT PA, 0001B ; SETTING ALL KEYPAD INPUT TO 1
		IN DL, PC
		CMP PC, 001B
		JE NUMBER1
		CMP PC, 010B
		JE NUMBER2
		CMP PC, 100B
		JE NUMBER3
		JMP LOOP_START
		
NUMBER1:
		MOV DH, 1
		JMP KEYPAD_BUTTON_FOUND
NUMBER2:
		MOV DH, 2
		JMP KEYPAD_BUTTON_FOUND
NUMBER3:
		MOV DH, 3
		JMP KEYPAD_BUTTON_FOUND
		
		
COLUMN2:
		OUT PA, 0001B ; SETTING ALL KEYPAD INPUT TO 1
		IN DL, PC
		CMP PC, 001B
		JE NUMBER4
		CMP PC, 010B
		JE NUMBER5
		CMP PC, 100B
		JE NUMBER6
		JMP LOOP_START
		
NUMBER4:
		MOV DH, 4
		JMP KEYPAD_BUTTON_FOUND
NUMBER5:
		MOV DH, 5
		JMP KEYPAD_BUTTON_FOUND
NUMBER6:
		MOV DH, 6
		JMP KEYPAD_BUTTON_FOUND
		
		
COLUMN3:
		OUT PA, 0001B ; SETTING ALL KEYPAD INPUT TO 1
		IN DL, PC
		CMP PC, 001B
		JE NUMBER7
		CMP PC, 010B
		JE NUMBER8
		CMP PC, 100B
		JE NUMBER9
		JMP LOOP_START
		
NUMBER7:
		MOV DH, 7
		JMP KEYPAD_BUTTON_FOUND
NUMBER8:
		MOV DH, 8
		JMP KEYPAD_BUTTON_FOUND
NUMBER9:
		MOV DH, 9
		JMP KEYPAD_BUTTON_FOUND
		
		
COLUMN4:
		OUT PA, 0001B ; SETTING ALL KEYPAD INPUT TO 1
		IN DL, PC
		CMP PC, 001B
		JE NUMBER10
		CMP PC, 010B
		JE NUMBER11
		CMP PC, 100B
		JE NUMBER12
		JMP LOOP_START
		
NUMBER10:
		MOV DH, 10
		JMP KEYPAD_BUTTON_FOUND
NUMBER11:
		MOV DH, 11
		JMP KEYPAD_BUTTON_FOUND
NUMBER12:
		MOV DH, 12
		JMP KEYPAD_BUTTON_FOUND
		
MAIN    ENDP

        END MAIN